name: "Choreo Test Image Build"
description: "build test images related to contract testing"
runs:
  using: "node16"
  main: "dist/index.js"
inputs:
  subPath:
    description: Path of the component repository
    required: true
    default: .
  testTempImageName:
    description: Temporary image name of the test image
    required: true
    default: testimagetemptag
  defaultPostmanCollectionPath:
    description: Default location of the test source file if not specified in the component.yaml
    required: true
    default: .choreo/postman.json
