name: "Choreo Test Image Build"
description: "build test images related to contract testing"
runs:
  using: "node16"
  main: "dist/index.js"
inputs:
  sub-path:
    description: Path of the component repository
    required: true
    default: .
  test-image-temp-name:
    description: Temporary image name of the test image
    required: true
    default: testimagetempname
  default-postman-path:
    description: Default location of the test source file if not specified in the component.yaml
    required: true
    default: .choreo/postman.json
